.PHONY: clean All

All:
	@echo "----------Building project:[ kitchen-cli - Release ]----------"
	@"$(MAKE)" -f  "kitchen-cli.mk"
clean:
	@echo "----------Cleaning project:[ kitchen-cli - Release ]----------"
	@"$(MAKE)" -f  "kitchen-cli.mk" clean
